FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /app/usr/share/nginx/html

CMD [ "nginx", "-g", "daemon=off;" ]